module.exports = {
   "installedPackages":{
      "xmlName":"InstalledPackage",
      "extension":"xml",
   },
   "labels":{
      "xmlName":"CustomLabels",
      "extension":"xml",
      "children":{
         "CustomLabels":{"xmlName":"CustomLabel","extension":"xml","name":"fullName"},
      }
   },
   "staticresources":{
      "xmlName":"StaticResource",
      "extension":"xml",
   },
   "scontrols":{
      "xmlName":"Scontrol",
      "extension":"xml",
   },
   "components":{
      "xmlName":"ApexComponent",
      "extension":"xml",
   },
   "customMetadata":{
      "xmlName":"CustomMetadata",
      "extension":"xml",
   },
   "globalValueSets":{
      "xmlName":"GlobalValueSet",
      "extension":"xml",
   },
   "globalValueSetTranslations":{
      "xmlName":"GlobalValueSetTranslation",
      "extension":"xml",
   },
   "standardValueSets":{
      "xmlName":"StandardValueSet",
      "extension":"xml",
   },
   "pages":{
      "xmlName":"ApexPage",
      "extension":"xml",
   },
   "queues":{
      "xmlName":"Queue",
      "extension":"xml",
   },
   "objects":{
      "xmlName":"CustomObject",
      "extension":"xml",
      "requiredField":"label",
      "children":{
         "fields":{"xmlName":"CustomField","extension":"xml","name":"fullName"},
         "businessProcesses":{"xmlName":"BusinessProcess","extension":"xml","name":"fullName"},
         "recordTypes":{"xmlName":"RecordType","extension":"xml","name":"fullName"},
         "webLinks":{"xmlName":"WebLink","extension":"xml","name":"fullName"},
         "validationRules":{"xmlName":"ValidationRule","extension":"xml","name":"fullName"},
         "namedFilters":{"xmlName":"NamedFilter","extension":"xml","name":"fullName"},
         "sharingReasons":{"xmlName":"SharingReason","extension":"xml","name":"fullName"},
         "listViews":{"xmlName":"ListView","extension":"xml","name":"fullName"},
         "fieldSets":{"xmlName":"FieldSet","extension":"xml","name":"fullName"},
         "compactLayouts":{"xmlName":"CompactLayout","extension":"xml","name":"fullName"}
      }
   },
   "reportTypes":{
      "xmlName":"ReportType",
      "extension":"xml",
   },
   "reports":{
      "metadataTypeFolder":'ReportFolder',
      "xmlName":"Report",
      "extension":"xml",
   },
   "dashboards":{
      "metadataTypeFolder":'DashboardFolder',
      "xmlName":"Dashboard",
      "extension":"xml",
   },
   "analyticSnapshots":{
      "xmlName":"AnalyticSnapshot",
      "extension":"xml",
   },
   "layouts":{
      "xmlName":"Layout",
      "extension":"xml",
   },
   "portals":{
      "xmlName":"Portal",
      "extension":"xml",
   },
   "documents":{
      "metadataTypeFolder":'DocumentFolder',
      "xmlName":"Document",
      "extension":"xml",
   },
   "weblinks":{
      "xmlName":"CustomPageWebLink",
      "extension":"xml",
   },
   "quickActions":{
      "xmlName":"QuickAction",
      "extension":"xml",
   },
   "flexipages":{
      "xmlName":"FlexiPage",
      "extension":"xml",
   },
   "tabs":{
      "xmlName":"CustomTab",
      "extension":"xml",
   },
   "customApplicationComponents":{
      "xmlName":"CustomApplicationComponent",
      "extension":"xml",
   },
   "applications":{
      "xmlName":"CustomApplication",
      "extension":"xml",
   },
   "letterhead":{
      "xmlName":"Letterhead",
      "extension":"xml",
   },
   "email":{
      "metadataTypeFolder":'EmailFolder',
      "xmlName":"EmailTemplate",
      "extension":"xml",
   },
   "workflows":{
      "xmlName":"Workflow",
      "extension":"xml",
      "requiredField":"",
      "children":{
         "alerts":{"xmlName":"WorkflowAlert","extension":"xml","name":"fullName"},
         "tasks":{"xmlName" : "WorkflowTask","extension":"xml","name" : "fullName"},
         "outboundMessages":{"xmlName" : "WorkflowOutboundMessage","extension":"xml","name" : "fullName"},
         "fieldUpdates":{"xmlName" : "WorkflowFieldUpdate","extension":"xml","name" : "fullName"},
         "rules":{"xmlName" : "WorkflowRule","extension":"xml","name" : "fullName"},
         "emailRecipients":{"xmlName" : "WorkflowEmailRecipient","extension":"xml","name" : "fullName"},
         "timeTriggers":{"xmlName" : "WorkflowTimeTrigger","extension":"xml","name" : "fullName"},
         "actionReferences":{"xmlName" : "WorkflowActionReference","extension":"xml","name" : "fullName"}
      }
   },
   "assignmentRules":{
      "xmlName":"AssignmentRules",
      "extension":"xml",
   },
   "autoResponseRules":{
      "xmlName":"AutoResponseRules",
      "extension":"xml",
   },
   "escalationRules":{
      "xmlName":"EscalationRules",
      "extension":"xml",
   },
   "roles":{
      "xmlName":"Role",
      "extension":"xml",
   },
   "groups":{
      "xmlName":"Group",
      "extension":"xml",
   },
   "postTemplates":{
      "xmlName":"PostTemplate",
      "extension":"xml",
   },
   "approvalProcesses":{
      "xmlName":"ApprovalProcess",
      "extension":"xml",
   },
   "homePageComponents":{
      "xmlName":"HomePageComponent",
      "extension":"xml",
   },
   "homePageLayouts":{
      "xmlName":"HomePageLayout",
      "extension":"xml",
   },
   "objectTranslations":{
      "xmlName":"CustomObjectTranslation",
      "extension":"xml",
   },
   "flows":{
      "xmlName":"Flow",
      "extension":"xml",
   },
   "classes":{
      "xmlName":"ApexClass",
      "extension":"cls",
   },
   "triggers":{
      "xmlName":"ApexTrigger",
      "extension":"xml",
   },
   "profiles":{
      "xmlName":"Profile",
      "extension":"xml",
   },
   "permissionsets":{
      "xmlName":"PermissionSet",
      "extension":"xml",
   },
   "datacategorygroups":{
      "xmlName":"DataCategoryGroup",
      "extension":"xml",
   },
   "remoteSiteSettings":{
      "xmlName":"RemoteSiteSetting",
      "extension":"xml",
   },
   "authproviders":{
      "xmlName":"AuthProvider",
      "extension":"xml",
   },
   "leadSharingRules":{
      "xmlName":"LeadSharingRules",
      "extension":"xml",
   },
   "campaignSharingRules":{
      "xmlName":"CampaignSharingRules",
      "extension":"xml",
   },
   "caseSharingRules":{
      "xmlName":"CaseSharingRules",
      "extension":"xml",
   },
   "contactSharingRules":{
      "xmlName":"ContactSharingRules",
      "extension":"xml",
   },
   "opportunitySharingRules":{
      "xmlName":"OpportunitySharingRules",
      "extension":"xml",
   },
   "accountSharingRules":{
      "xmlName":"AccountSharingRules",
      "extension":"xml",
   },
   "customObjectSharingRules":{
      "xmlName":"CustomObjectSharingRules",
      "extension":"xml",
   },
   "communities":{
      "xmlName":"Community",
      "extension":"xml",
   },
   "callCenters":{
      "xmlName":"CallCenter",
      "extension":"xml",
   },
   "connectedApps":{
      "xmlName":"ConnectedApp",
      "extension":"xml",
   },
   "samlssoconfigs":{
      "xmlName":"SamlSsoConfig",
      "extension":"xml",
   },
   "synonymDictionaries":{
      "xmlName":"SynonymDictionary",
      "extension":"xml",
   },
   "settings":{
      "xmlName":"Settings",
      "extension":"xml",
   },
   "aura":{
      "xmlName":"AuraDefinitionBundle",
      "extension":"xml",
   },
   "sharingRules":{
      "xmlName":"SharingRules",
      "extension":"xml",
      "children":{
         "sharingTerritoryRules":{"xmlName":"SharingTerritoryRule","extension":"xml","name":"fullName"},
         "sharingOwnerRules":{"xmlName":"SharingOwnerRule","extension":"xml","name":"fullName"},
         "sharingCriteriaRules":{"xmlName":"SharingCriteriaRule","extension":"xml","name":"fullName"},
      }
   },
   "contentassets":{
      "xmlName":"ContentAsset",
      "extension":"xml",
   },
   "networks":{
      "xmlName":"Network",
      "extension":"xml",
   },
   "siteDotComSites":{
      "xmlName":"SiteDotCom",
      "extension":"xml",
   },
   "flowDefinitions":{
      "xmlName":"FlowDefinition",
      "extension":"xml",
   },
   "matchingRules":{
      "xmlName":"MatchingRules",
      "extension":"xml",
   },
   "appMenu":{
      "xmlName":"AppMenu",
      "extension":"xml",
   },
   "campaignInfluenceModels":{
      "xmlName":"CampaignInfluenceModel",
      "extension":"xml",
   },
   "cleanDataServices":{
      "xmlName":"CleanDataService",
      "extension":"xml",
   },
   "duplicateRules":{
      "xmlName":"DuplicateRule",
      "extension":"xml",
   },
   "managedTopics":{
      "xmlName":"ManagedTopics",
      "extension":"xml",
   },
   "moderation":{
      "xmlName":"ModerationRule",
      "extension":"xml",
   },
   "networkBranding":{
      "xmlName":"NetworkBranding",
      "extension":"xml",
   },
   "pathAssistants":{
      "xmlName":"PathAssistant",
      "extension":"xml",
   },
   "profilePasswordPolicies":{
      "xmlName":"ProfilePasswordPolicy",
      "extension":"xml",
   },
   "profileSessionSettings":{
      "xmlName":"ProfileSessionSetting",
      "extension":"xml",
   },
   "certs":{
      "xmlName":"Certificate",
      "extension":"xml",
   },
   "topicsForObjects":{
      "xmlName":"TopicsForObjects",
      "extension":"xml",
   },
   "userCriteria":{
      "xmlName":"UserCriteria",
      "extension":"xml",
   },
   "emailservices":{
      "xmlName":"EmailServicesFunction",
      "extension":"xml",
   },
   "sites":{
      "xmlName":"CustomSite",
      "extension":"xml",
   },
   "customPermissions":{  
      "xmlName":"CustomPermission",
      "extension":"xml",
   },
   "standardValueSetTranslations":{
      "xmlName":"StandardValueSetTranslation",
      "extension":"xml",
   },   
   "translations":{
      "xmlName":"Translations",
      "extension":"xml",
   },
};